from selenium.webdriver.common.by import By
from selenium import webdriver
import time
import pyautogui
import pyperclip
from PyQt5.Qtwidgets import QApplication,QMainwindow
from Pyot5.QtGui import QIcon
import sys
import random
import pygame
import os
import ks
from PyQt5 import QtCore,QtGui,QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(512, 436)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(-10, 0, 521, 391))
        self.label_22.setStyleSheet("border-image: url(:/BACK/109...jpg);")
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(150, 220, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(420, 20, 75, 23))
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(290, 120, 111, 21))
        self.label_28.setObjectName("label_28")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(420, 170, 75, 23))
        self.pushButton_13.setObjectName("pushButton_13")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(20, 70, 111, 21))
        self.label_18.setObjectName("label_18")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(20, 220, 111, 21))
        self.label_21.setObjectName("label_21")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 70, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(420, 220, 75, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(150, 20, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(20, 120, 111, 21))
        self.label_19.setObjectName("label_19")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(150, 170, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(420, 70, 75, 23))
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(290, 170, 111, 21))
        self.label_29.setObjectName("label_29")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(290, 220, 111, 21))
        self.label_31.setObjectName("label_31")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(290, 70, 111, 21))
        self.label_30.setObjectName("label_30")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(150, 120, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(20, 20, 101, 21))
        self.label_17.setObjectName("label_17")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(20, 170, 111, 21))
        self.label_20.setObjectName("label_20")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(420, 120, 75, 23))
        self.pushButton_15.setObjectName("pushButton_15")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(290, 20, 111, 21))
        self.label_27.setObjectName("label_27")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 340, 71, 51))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(70, 350, 151, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 340, 71, 51))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(340, 350, 161, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(20, 270, 111, 21))
        self.label_23.setObjectName("label_23")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(150, 270, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(290, 270, 111, 21))
        self.label_24.setObjectName("label_24")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(420, 270, 75, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(230, 350, 51, 31))
        self.pushButton_8.setObjectName("pushButton_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 512, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PPN"))
        self.pushButton_5.setText(_translate("MainWindow", "运行"))
        self.pushButton_14.setText(_translate("MainWindow", "运行"))
        self.label_28.setText(_translate("MainWindow", "打开电脑适配器："))
        self.pushButton_13.setText(_translate("MainWindow", "运行"))
        self.label_18.setText(_translate("MainWindow", "打开NBA东西部排名："))
        self.label_21.setText(_translate("MainWindow", "小游戏："))
        self.pushButton_2.setText(_translate("MainWindow", "运行"))
        self.pushButton_11.setText(_translate("MainWindow", "运行"))
        self.pushButton.setText(_translate("MainWindow", "运行"))
        self.label_19.setText(_translate("MainWindow", "打开CSDN学习："))
        self.pushButton_4.setText(_translate("MainWindow", "运行"))
        self.pushButton_12.setText(_translate("MainWindow", "运行"))
        self.label_29.setText(_translate("MainWindow", "打开设备管理器："))
        self.label_31.setText(_translate("MainWindow", "打开Mysql数据库："))
        self.label_30.setText(_translate("MainWindow", "打开CSDN我的内容："))
        self.pushButton_3.setText(_translate("MainWindow", "运行"))
        self.label_17.setText(_translate("MainWindow", "打开NBA图文数据："))
        self.label_20.setText(_translate("MainWindow", "打开翻译："))
        self.pushButton_15.setText(_translate("MainWindow", "运行"))
        self.label_27.setText(_translate("MainWindow", "打开图片转换工具："))
        self.label.setText(_translate("MainWindow", "搜索："))
        self.label_2.setText(_translate("MainWindow", "返回："))
        self.label_23.setText(_translate("MainWindow", "打开计算器："))
        self.pushButton_6.setText(_translate("MainWindow", "运行"))
        self.label_24.setText(_translate("MainWindow", "打开记事本："))
        self.pushButton_7.setText(_translate("MainWindow", "运行"))
        self.pushButton_8.setText(_translate("MainWindow", "run"))


import TUTU_rc